### PR TITLE
Avoid unnecessary and unsound transmute

### LINKED ISSUE #27: Wrong unsafe
It's wrong using `unsafe { *mem::transmute::<_, *const f64>(self) }`

https://doc.rust-lang.org/reference/type-layout.html#the-default-representation

> There are no guarantees of data layout made by this representation.

Why not just self.x, self.y and so ones

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #27

### CODE REVIEW

File: src/ewkb.rs [hunk 1]
```diff
@@ -182,10 +181,10 @@ impl Point {
 
 impl postgis::Point for Point {
     fn x(&self) -> f64 {
-        unsafe { *mem::transmute::<_, *const f64>(self) }
+        self.x
     }
     fn y(&self) -> f64 {
-        unsafe { *mem::transmute::<_, *const f64>(self).offset(1) }
```
Comment (mmarkov) [inline src/ewkb.rs:188]: Thank you a ton for fixing this. I am using postgis on Mac M1 with debug build and my memory looks totally different. So this transmute pulls totally wrong data instead of x,y. 
Screenshot 2025-08-11 at 6 46 03 PM
